name: CI

on:
  push:
  workflow_dispatch:

jobs:
  verify:
    name: Verify module
    uses: ./.github/workflows/sub_verify.yaml

  publish:
    name: Publish package
    uses: ./.github/workflows/sub_publish.yaml
