name: CI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  deployments: write
  packages: write


jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/sub_verify.yaml

  publish_prerelease:
    name: Prerelease
    needs:
      - verify
    uses: ./.github/workflows/sub_publish_prerelease.yaml
