name: CI

on:
  push:
  workflow_dispatch:

permissions:
   # This is required for actions/checkout
  contents: read
  # Allow cancel job
  actions: write
  # Allow create new deployments
  deployments: write
  # Allow upload package
  packages: write


jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/sub_verify.yaml

  publish_prerelease:
    name: Prerelease
    needs:
      - verify
    uses: ./.github/workflows/sub_publish_prerelease.yaml
    secrets: inherit

  publish_release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs:
      - publish_prerelease
    uses: ./.github/workflows/sub_publish_release.yaml
    secrets: inherit

  