name: Sub Publish Prerelease

on:
  workflow_call:

jobs:
  publish:
    name: Publish prerelease to GitHub Package Repository
    runs-on: ubuntu-latest
    environment:
      name: gpr
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Package
        merge_multiple: true
        #pattern: '*.nupkg'

    - name: Upload Github package
      shell: pwsh
      env:
        GPR_SECRET: ${{ secrets.GPR_SECRET }}
      run: |
        dotnet tool install --global gpr --version 0.1.294
        gpr push -k "$env:GPR_SECRET" (Resolve-Path "*.nupkg") -r https://github.com/${{github.repository}}

    #- name: Publish
    #  shell: pwsh
    #  env:
    #    NUGET_KEY: ${{ secrets.PSGALLERY_SECRET }}
    #  run: |
    #    Publish-Module -path ./src/SitecoreCecSearchModule/1.0.0 -NuGetApiKey $env:NUGET_KEY -Verbose -ProjectUri -IconUri -AllowPrerelease

          
    # - name: Create github release tag
    #   if: success() && github.ref == 'refs/heads/master'
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: v${{ env.BUILD_VERSION }}
    #     release_name: Release v${{ env.BUILD_VERSION }}
    #     draft: true
    #     prerelease: false
