name: Sub Publish Release

on:
  workflow_call:

jobs:
  publish:
    name: Publish Release to PSGallery
    runs-on: ubuntu-latest
    environment:
      name: psgallery
    outputs:
      version: ${{ steps.version.outputs.full_version }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: GitVersion install
      shell: pwsh
      run: |
        dotnet tool install --global GitVersion.Tool --version 5.*

    - name: Update version
      shell: pwsh
      id: version
      run: |
        $versions = dotnet-gitversion /config .\bld\GitVersion.yml /output json | Out-String | ConvertFrom-Json
        Write-Host "GitVersion output"
        $versions

        $no = $versions.CommitsSinceVersionSourcePadded
        $version = $versions.MajorMinorPatch
        $prerelease = ("{0}" -f $versions.NuGetPreReleaseTagV2)
        $branch = $versions.PreReleaseLabel

        If("${{github.ref_name }}" -match "refs/pull/([0-9]+)/merge") {
          $pr = $Matches[1]
          $prerelease = "alpha${pr}pr${no}"
        } ElseIf("$branch" -ne "main") {
          $prerelease = "beta${branch}${no}"
        } ElseIf ("$branch" -eq "main" -and "${prerelease}" -eq "") {
          $prerelease = "rc${no}"
        }

        $fullversion = (@($version, $prerelease) | Where-object { $_ -ne "" }) -join "-"

        echo ("version={0}" -f $version) >> "$env:GITHUB_OUTPUT"
        echo ("prerelease={0}" -f $prerelease) >> "$env:GITHUB_OUTPUT"
        echo ("full_version={0}" -f $fullversion) >> "$env:GITHUB_OUTPUT"
        echo ("is_prerelease={0}" -f ("${prerelease}" -ne "")) >> "$env:GITHUB_OUTPUT"

        $versionParams = @{
          Path = "./src/SitecoreCecSearchModule/SitecoreCecSearchModule.psd1"
          ModuleVersion = $version
        }
        if("${prerelease}" -ne "") {
          $versionParams.Prerelease = $prerelease
        }

        Write-Host ("Update version to {0}" -f $fullversion)
        Update-ModuleManifest @versionParams

    - name: Publish
      shell: pwsh
      env:
        NUGETKEY: ${{ secrets.NUGET_APIKEY }}
      run: |
        Install-Module Microsoft.PowerShell.PSResourceGet -Repository PSGallery -Force
        Publish-PSResource -path ./src/SitecoreCecSearchModule -Repository PSGallery -APIKey "${env:NUGETKEY}" -Verbose

  verify:
    name: Verify published package
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: false
          fetch-depth: 1
      - name: Install package
        shell: pwsh
        run: |
          ./bld/Install-ReleasedPackage.ps1 -Version ${{ needs.publish.outputs.version }}

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - publish
      - verify
    steps:
    - name: Create github release tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: v${{ needs.publish.outputs.version }}
        release_name: Release v${{ needs.publish.outputs.version }}
        draft: true
        prerelease: ${{ needs.publish.outputs.is_prerelease != 'false' }}
