name: Sub Build

on:
  workflow_call:

jobs:
  build:
    name: Create nuget package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Update version
      shell: pwsh
      run: |
        dotnet tool install --global GitVersion.Tool --version 5.*
        $ver = dotnet-gitversion /config .\bld\GitVersion.yml /output json | Out-String | ConvertFrom-Json
        $versionParams = @{
          Path = "./src/SitecoreCecSearchModule/SitecoreCecSearchModule.psd1"
          ModuleVersion = $ver.MajorMinorPatch
        }
        if(("{0}" -f $ver.NuGetPreReleaseTagV2) -ne "") {
          $versionParams.Prerelease = $ver.NuGetPreReleaseTagV2
        }

        Update-ModuleManifest @versionParams

    - name: Create NuGet package
      shell: pwsh
      run: |
        $repoPath = (Join-Path $PWD "publish")
        If(-not (Test-Path $repoPath -PathType Container)) { New-Item $repoPath -ItemType Directory | Out-Null }

        Install-Module Microsoft.PowerShell.PSResourceGet -Repository PSGallery -Force
        Register-PSResourceRepository -Name nuget-local -Uri $repoPath
        Publish-PSResource -Path ./src/SitecoreCecSearchModule -Repository "nuget-local"
        
    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: publish/*.nupkg
